# Generated by Django 4.1.1 on 2022-09-14 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyecto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiares',
            name='fechaNac',
            field=models.DateTimeField(verbose_name=30),
        ),
    ]
