# Generated by Django 4.1.1 on 2022-09-14 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyecto', '0002_alter_familiares_fechanac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiares',
            name='fechaNac',
            field=models.DateTimeField(),
        ),
    ]
