# Generated by Django 4.1.1 on 2022-09-22 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyecto', '0003_alter_familiares_fechanac'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('procedencia', models.CharField(max_length=60)),
                ('division', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('apellido', models.CharField(max_length=60)),
                ('edad', models.IntegerField()),
                ('puesto', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Liga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('pais', models.CharField(max_length=60)),
                ('division', models.CharField(max_length=60)),
            ],
        ),
        migrations.AlterField(
            model_name='familiares',
            name='fechaNac',
            field=models.DateField(),
        ),
    ]
